### PR TITLE
port to GTK+3

### PR DESCRIPTION
**Pull request by yell0wfl4sh**
@quozl  please review!

### CODE REVIEW

**Comment by chimosky** [comment]
@yashagrawal3 activity opens and closes almost immediately.

**Comment by quozl** [comment]
@chimosky, check the activity log, or stdout from sugar-activity in terminal.  Your system may not have the required version of Vte installed.

**Comment by chimosky** [comment]
@quozl i do have Vte version `2.91` and stdout doesn't have any information.

**Comment by quozl** [comment]
@chimosky, stdout won't have errors, that's for stderr.  Use pdb and step through it?  What operating system and Sugar version?

@yashagrawal3, does the activity work for you?  What operating system and Sugar version?

**Comment by yell0wfl4sh** [comment]
It works fine for me, I use ubuntu 17.10 and sugar v0.112

**Comment by chimosky** [comment]
@quozl I'll comment what i have on pdb once I've stepped through it but i tried gdb and i got this
```
[New Thread 0x7fffe8ae4700 (LWP 11861)]
[New Thread 0x7fffe3fff700 (LWP 11862)]
[New Thread 0x7fffe37fe700 (LWP 11863)]
/usr/lib/python2.7/sugar3/activity/activity.py:96: PyGIWarning: SugarExt was imported without specifying a version first. Use gi.require_version('SugarExt', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import SugarExt

(sugar-activity:11854): Gtk-WARNING **: 16:10:48.872: Theme parsing error: gtk-widgets.css:16:32: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(sugar-activity:11854): Gtk-WARNING **: 16:10:48.872: Theme parsing error: gtk-widgets.css:17:35: The style property GtkExpander:expander-spacing is deprecated and shouldn't be used anymore. It will be removed in a future version
1531494649.563413 WARNING root: Telepathy Account dbus.ObjectPath('/org/freedesktop/Telepathy/Account/idle/irc/ibiam0') does not support Sugar collaboration
[Thread 0x7fffe37fe700 (LWP 11863) exited]
[Thread 0x7fffe3fff700 (LWP 11862) exited]
[Thread 0x7fffe8ae4700 (LWP 11861) exited]
[Inferior 1 (process 11854) exited normally]
```
> What operating system and Sugar version?

Arch Linux - *about to move to Fedora* -, sugar0.112

**Comment by quozl** [comment]
@chimosky, thanks, that's not a recent version of Sugar, the SugarExt warning was turned off about two years ago, see https://github.com/sugarlabs/sugar-toolkit-gtk3/blame/master/src/sugar3/activity/activity.py#L175

**Pull request merged**
